nuxt3 に変更

diff --git a/.github/workflows/webhook.yml b/.github/workflows/webhook.yml
--- a/.github/workflows/webhook.yml
+++ b/.github/workflows/webhook.yml
@@ -10,32 +10,53 @@ jobs:
   webhook_build:
     name: Build(from webhook)
     runs-on: ubuntu-latest
-    # webhook-deploy のときだけ動かす
-    if: github.event_name == 'repository_dispatch' && github.event.action == 'webhook-deploy'
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
-        with:
-          ref: main   # ← ここは main / stage など、デプロイしたいブランチに合わせて
       - name: Use Node.js
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: '16.x'
+          node-version: '20.x'
+      - name: CI Cache
+        uses: actions/cache@v4
+        id: node_modules_cache_id
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: '**/node_modules'
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
       - name: Install dependencies
+        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
         run: npm ci
-      - name: Build
-        run: npm run build
+
       - name: Generate
         run: npm run generate
+      - name: Validate kuroco_front.json
+        run: |
+          if [ -f "./.output/public/kuroco_front.json" ]; then
+            echo "kuroco_front.json found"
+            # JSON形式の検証
+            if jq empty ./.output/public/kuroco_front.json; then
+              echo "kuroco_front.json is valid JSON"
+            else
+              echo "Error: kuroco_front.json is not valid JSON"
+              exit 1
+            fi
+          else
+            echo "Error: kuroco_front.json not found in public folder"
+            exit 1
+          fi
+      - name: Zip artifact for upload
+        run: cd ./.output/public && zip ../../dist.zip . -r
       - name: Archive Production Artifact
         uses: actions/upload-artifact@v4
         with:
           name: ${{ github.sha }}-${{ github.run_id }}
-          path: dist
+          path: dist.zip
           retention-days: 7
       - name: Webhook
-        uses: diverta/workflow-webhook@v2
-        env:
+        uses: diverta/workflow-webhook@v3
+        with:
           webhook_url: "https://hasebe.g.kuroco.app/direct/menu/github/"
-          webhook_secret: "6058cc0d39746b2a6781d4fc2e2c70fd"
-          data: '{"single_zip":"0","domain":"hasebe.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
+          webhook_secret: "7c0efe0b7bc988439947edb66434f459"
+          data: '{"single_zip":"1","domain":"hasebe.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
